spring.datasource.url=jdbc:mysql://localhost:3306/jwtdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=mysupersecuresecretkeygtrhfnbfjcsiuabfdbmbmbma263r483w92yicbk
jwt.expiration=3600000